export const formConfig = {
  steps: [
    {
      id: "company",
      title: "Company Information",
      description: "Basic company and contact details",
      fields: [
        {
          id: "companyName",
          label: "Company Name",
          type: "text",
          required: true,
          placeholder: "Enter company name",
          validation: {
            minLength: 2,
            maxLength: 100,
          },
        },
        {
          id: "contactPerson",
          label: "Contact Person",
          type: "text",
          required: true,
          placeholder: "Enter contact person name",
          validation: {
            minLength: 2,
            maxLength: 50,
          },
        },
        {
          id: "email",
          label: "Email Address",
          type: "email",
          required: true,
          placeholder: "Enter email address",
          validation: {
            pattern: "^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$",
          },
        },
        {
          id: "phone",
          label: "Phone Number",
          type: "tel",
          required: true,
          placeholder: "Enter phone number",
          validation: {
            pattern: "^[+]?[0-9\\s\\-$$$$]{10,}$",
          },
        },
        {
          id: "companyAddress",
          label: "Company Address",
          type: "textarea",
          required: false,
          placeholder: "Enter complete address",
          rows: 3,
        },
      ],
    },
    {
      id: "shipment",
      title: "Shipment Details",
      description: "Transportation and routing information",
      fields: [
        {
          id: "shipmentType",
          label: "Shipment Type",
          type: "select",
          required: true,
          placeholder: "Select shipment type",
          options: [
            { value: "air", label: "Air Freight" },
            { value: "sea", label: "Sea Freight" },
            { value: "land", label: "Land Transport" },
            { value: "multimodal", label: "Multimodal" },
          ],
        },
        {
          id: "origin",
          label: "Origin",
          type: "text",
          required: true,
          placeholder: "City, Country",
        },
        {
          id: "destination",
          label: "Destination",
          type: "text",
          required: true,
          placeholder: "City, Country",
        },
        {
          id: "expectedDelivery",
          label: "Expected Delivery Date",
          type: "date",
          required: false,
        },
        {
          id: "trackingNumber",
          label: "Tracking Number",
          type: "text",
          required: false,
          placeholder: "Enter tracking number if available",
        },
      ],
    },
    {
      id: "cargo",
      title: "Cargo Information",
      description: "Details about the cargo being shipped",
      fields: [
        {
          id: "cargoDescription",
          label: "Cargo Description",
          type: "textarea",
          required: true,
          placeholder: "Detailed description of the cargo",
          rows: 3,
          validation: {
            minLength: 10,
            maxLength: 500,
          },
        },
        {
          id: "weight",
          label: "Weight (kg)",
          type: "number",
          required: true,
          placeholder: "0.00",
          validation: {
            min: 0.1,
            max: 50000,
          },
        },
        {
          id: "dimensions",
          label: "Dimensions (L×W×H cm)",
          type: "text",
          required: true,
          placeholder: "100×50×30",
          validation: {
            pattern: "^\\d+×\\d+×\\d+$",
          },
        },
        {
          id: "value",
          label: "Declared Value (USD)",
          type: "number",
          required: true,
          placeholder: "0.00",
          validation: {
            min: 1,
            max: 1000000,
          },
        },
        {
          id: "hsCode",
          label: "HS Code",
          type: "text",
          required: false,
          placeholder: "Enter HS classification code",
        },
      ],
    },
    {
      id: "options",
      title: "Additional Options",
      description: "Insurance, priority, and special requirements",
      fields: [
        {
          id: "insuranceRequired",
          label: "Insurance Required",
          type: "checkbox",
          required: false,
          defaultValue: false,
        },
        {
          id: "priorityLevel",
          label: "Priority Level",
          type: "radio",
          required: true,
          options: [
            { value: "standard", label: "Standard" },
            { value: "express", label: "Express" },
            { value: "urgent", label: "Urgent" },
          ],
        },
        {
          id: "specialInstructions",
          label: "Special Instructions",
          type: "textarea",
          required: false,
          placeholder: "Any special handling requirements or instructions",
          rows: 3,
        },
        {
          id: "dangerousGoods",
          label: "Contains Dangerous Goods",
          type: "checkbox",
          required: false,
          defaultValue: false,
        },
        {
          id: "temperatureControlled",
          label: "Temperature Controlled",
          type: "checkbox",
          required: false,
          defaultValue: false,
        },
      ],
    },
  ],
}
