// Common blockchain fields step for all documents
const blockchainFieldsStep = {
  id: "blockchain-details",
  title: "Blockchain & Ownership Details",
  description: "Configure document ownership and blockchain parameters",
  fields: [
    {
      id: "owner",
      label: "Owner Address",
      type: "text",
      required: true,
      placeholder: "Enter Ethereum address (e.g., 0x8e215d06ea7ec1fdb4fc5fd21768f4b34ee92ef4)",
    },
    {
      id: "holder",
      label: "Holder Address",
      type: "text",
      required: true,
      placeholder: "Enter Ethereum address (e.g., 0x8e215d06ea7ec1fdb4fc5fd21768f4b34ee92ef4)",
    },
    {
      id: "remarks",
      label: "Remarks (Optional)",
      type: "textarea",
      required: false,
      placeholder: "Add private notes or comments (will be encrypted on blockchain)",
      rows: 3,
    },
  ],
};

// Electronic Promissory Note Form Config
export const electronicPromissoryNoteConfig = {
  steps: [
    blockchainFieldsStep,
    {
      id: "epn-basic-details",
      title: "Basic Note Information",
      description: "Essential promissory note details",
      fields: [
        {
          id: "epnId",
          label: "EPN ID",
          type: "text",
          required: true,
          placeholder: "Auto-generated",
          readonly: true,
        },
        {
          id: "promissoryNoteNumber",
          label: "Promissory Note Number",
          type: "text",
          required: true,
          placeholder: "Enter note number",
        },
        {
          id: "documentIdentifier",
          label: "Document Identifier",
          type: "text",
          required: false,
          placeholder: "Enter document identifier",
        },
        {
          id: "issueDate",
          label: "Issue Date",
          type: "date",
          required: true,
        },
        {
          id: "issuePlace",
          label: "Issue Place",
          type: "text",
          required: true,
          placeholder: "Enter place of issue",
        },
        {
          id: "maturityDate",
          label: "Maturity Date",
          type: "date",
          required: true,
        },
        {
          id: "paymentDueDate",
          label: "Payment Due Date",
          type: "date",
          required: true,
        },
      ],
    },
    {
      id: "epn-parties",
      title: "Parties Information",
      description: "Maker, Payee, and Beneficiary details",
      fields: [
        {
          id: "makerName",
          label: "Maker Name",
          type: "text",
          required: true,
          placeholder: "Enter maker's name",
        },
        {
          id: "makerAddress",
          label: "Maker Address",
          type: "textarea",
          required: true,
          placeholder: "Enter maker's address",
          rows: 3,
        },
        {
          id: "makerId",
          label: "Maker ID",
          type: "text",
          required: false,
          placeholder: "Enter maker's ID",
        },
        {
          id: "makerTaxId",
          label: "Maker Tax ID",
          type: "text",
          required: false,
          placeholder: "Enter maker's tax ID",
        },
        {
          id: "makerContact",
          label: "Maker Contact",
          type: "text",
          required: false,
          placeholder: "Enter maker's contact",
        },
        {
          id: "payeeName",
          label: "Payee Name",
          type: "text",
          required: true,
          placeholder: "Enter payee's name",
        },
        {
          id: "payeeAddress",
          label: "Payee Address",
          type: "textarea",
          required: true,
          placeholder: "Enter payee's address",
          rows: 3,
        },
        {
          id: "payeeId",
          label: "Payee ID",
          type: "text",
          required: false,
          placeholder: "Enter payee's ID",
        },
        {
          id: "payeeBankAccount",
          label: "Payee Bank Account",
          type: "text",
          required: false,
          placeholder: "Enter payee's bank account",
        },
        {
          id: "beneficiaryName",
          label: "Beneficiary Name",
          type: "text",
          required: false,
          placeholder: "Enter beneficiary's name",
        },
        {
          id: "beneficiaryAddress",
          label: "Beneficiary Address",
          type: "textarea",
          required: false,
          placeholder: "Enter beneficiary's address",
          rows: 3,
        },
        {
          id: "beneficiaryAccount",
          label: "Beneficiary Account",
          type: "text",
          required: false,
          placeholder: "Enter beneficiary's account",
        },
      ],
    },
    {
      id: "epn-payment",
      title: "Payment Details",
      description: "Amount and payment information",
      fields: [
        {
          id: "principalAmount",
          label: "Principal Amount",
          type: "number",
          required: true,
          placeholder: "0.00",
        },
        {
          id: "currency",
          label: "Currency",
          type: "select",
          required: true,
          options: [
            { value: "USD", label: "US Dollar (USD)" },
            { value: "EUR", label: "Euro (EUR)" },
            { value: "GBP", label: "British Pound (GBP)" },
            { value: "SGD", label: "Singapore Dollar (SGD)" },
            { value: "JPY", label: "Japanese Yen (JPY)" },
          ],
        },
        {
          id: "amountInWords",
          label: "Amount in Words",
          type: "text",
          required: false,
          placeholder: "Enter amount in words",
        },
        {
          id: "interestRate",
          label: "Interest Rate (%)",
          type: "number",
          required: false,
          placeholder: "0.00",
        },
        {
          id: "interestCalculationMethod",
          label: "Interest Calculation Method",
          type: "text",
          required: false,
          placeholder: "Enter interest calculation method",
        },
        {
          id: "totalAmountPayable",
          label: "Total Amount Payable",
          type: "number",
          required: false,
          placeholder: "Auto-calculated (Principal + Interest)",
          readonly: true,
          computed: true,
        },
        {
          id: "paymentTerms",
          label: "Payment Terms",
          type: "textarea",
          required: false,
          placeholder: "Enter payment terms",
          rows: 3,
        },
        {
          id: "paymentMethod",
          label: "Payment Method",
          type: "text",
          required: false,
          placeholder: "Enter payment method",
        },
        {
          id: "paymentPlace",
          label: "Payment Place",
          type: "text",
          required: false,
          placeholder: "Enter payment place",
        },
        {
          id: "paymentInstructions",
          label: "Payment Instructions",
          type: "textarea",
          required: false,
          placeholder: "Enter payment instructions",
          rows: 3,
        },
      ],
    },
    {
      id: "epn-banking",
      title: "Banking Information",
      description: "Bank details for payment",
      fields: [
        {
          id: "bankName",
          label: "Bank Name",
          type: "text",
          required: false,
          placeholder: "Enter bank name",
        },
        {
          id: "bankAddress",
          label: "Bank Address",
          type: "textarea",
          required: false,
          placeholder: "Enter bank address",
          rows: 3,
        },
        {
          id: "bankSwiftCode",
          label: "Bank SWIFT Code",
          type: "text",
          required: false,
          placeholder: "Enter SWIFT code",
        },
        {
          id: "bankAccountNumber",
          label: "Bank Account Number",
          type: "text",
          required: false,
          placeholder: "Enter bank account number",
        },
        {
          id: "bankRoutingNumber",
          label: "Bank Routing Number",
          type: "text",
          required: false,
          placeholder: "Enter bank routing number",
        },
      ],
    },
    {
      id: "epn-terms",
      title: "Terms & Conditions",
      description: "Legal terms and transferability",
      fields: [
        {
          id: "isNegotiable",
          label: "Is Negotiable",
          type: "select",
          required: true,
          options: [
            { value: "true", label: "Yes" },
            { value: "false", label: "No" },
          ],
        },
        {
          id: "isTransferable",
          label: "Is Transferable",
          type: "select",
          required: true,
          options: [
            { value: "true", label: "Yes" },
            { value: "false", label: "No" },
          ],
        },
        {
          id: "transferRestrictions",
          label: "Transfer Restrictions",
          type: "textarea",
          required: false,
          placeholder: "Enter any transfer restrictions",
          rows: 3,
        },
        {
          id: "governingLaw",
          label: "Governing Law",
          type: "text",
          required: false,
          placeholder: "Enter governing law",
        },
        {
          id: "disputeResolution",
          label: "Dispute Resolution",
          type: "textarea",
          required: false,
          placeholder: "Enter dispute resolution terms",
          rows: 3,
        },
        {
          id: "termsAndConditions",
          label: "Terms and Conditions",
          type: "textarea",
          required: false,
          placeholder: "Enter terms and conditions",
          rows: 4,
        },
      ],
    },
  ],
}

// Warehouse Receipt Form Config
export const warehouseReceiptConfig = {
  steps: [
    blockchainFieldsStep,
    {
      id: "wr-basic-details",
      title: "Receipt Information",
      description: "Basic warehouse receipt details",
      fields: [
        {
          id: "wrId",
          label: "Warehouse Receipt ID",
          type: "text",
          required: true,
          placeholder: "Auto-generated",
          readonly: true,
        },
        {
          id: "receiptNumber",
          label: "Receipt Number",
          type: "text",
          required: true,
          placeholder: "Enter receipt number",
        },
        {
          id: "documentIdentifier",
          label: "Document Identifier",
          type: "text",
          required: false,
          placeholder: "Enter document identifier",
        },
        {
          id: "issueDate",
          label: "Issue Date",
          type: "date",
          required: true,
        },
        {
          id: "receiptDate",
          label: "Receipt Date",
          type: "date",
          required: true,
        },
        {
          id: "expiryDate",
          label: "Expiry Date",
          type: "date",
          required: false,
        },
        {
          id: "storageStartDate",
          label: "Storage Start Date",
          type: "date",
          required: false,
        },
        {
          id: "storageEndDate",
          label: "Storage End Date",
          type: "date",
          required: false,
        },
      ],
    },
    {
      id: "wr-parties",
      title: "Parties Information",
      description: "Warehouse keeper, depositor, and holder details",
      fields: [
        {
          id: "warehouseKeeperName",
          label: "Warehouse Keeper Name",
          type: "text",
          required: true,
          placeholder: "Enter warehouse keeper name",
        },
        {
          id: "warehouseKeeperAddress",
          label: "Warehouse Keeper Address",
          type: "textarea",
          required: true,
          placeholder: "Enter warehouse keeper address",
          rows: 3,
        },
        {
          id: "warehouseKeeperLicense",
          label: "Warehouse Keeper License",
          type: "text",
          required: false,
          placeholder: "Enter license number",
        },
        {
          id: "warehouseKeeperContact",
          label: "Warehouse Keeper Contact",
          type: "text",
          required: false,
          placeholder: "Enter contact information",
        },
        {
          id: "depositorName",
          label: "Depositor Name",
          type: "text",
          required: true,
          placeholder: "Enter depositor name",
        },
        {
          id: "depositorAddress",
          label: "Depositor Address",
          type: "textarea",
          required: true,
          placeholder: "Enter depositor address",
          rows: 3,
        },
        {
          id: "depositorId",
          label: "Depositor ID",
          type: "text",
          required: false,
          placeholder: "Enter depositor ID",
        },
        {
          id: "depositorContact",
          label: "Depositor Contact",
          type: "text",
          required: false,
          placeholder: "Enter depositor contact",
        },
        {
          id: "holderName",
          label: "Holder Name",
          type: "text",
          required: false,
          placeholder: "Enter holder name",
        },
        {
          id: "holderAddress",
          label: "Holder Address",
          type: "textarea",
          required: false,
          placeholder: "Enter holder address",
          rows: 3,
        },
        {
          id: "holderId",
          label: "Holder ID",
          type: "text",
          required: false,
          placeholder: "Enter holder ID",
        },
      ],
    },
    {
      id: "wr-warehouse-location",
      title: "Warehouse Location",
      description: "Warehouse facility details",
      fields: [
        {
          id: "warehouseName",
          label: "Warehouse Name",
          type: "text",
          required: true,
          placeholder: "Enter warehouse name",
        },
        {
          id: "warehouseAddress",
          label: "Warehouse Address",
          type: "textarea",
          required: true,
          placeholder: "Enter warehouse address",
          rows: 3,
        },
        {
          id: "warehouseCode",
          label: "Warehouse Code",
          type: "text",
          required: false,
          placeholder: "Enter warehouse code",
        },
        {
          id: "warehouseCountry",
          label: "Warehouse Country",
          type: "text",
          required: false,
          placeholder: "Enter country",
        },
        {
          id: "warehouseZone",
          label: "Warehouse Zone",
          type: "text",
          required: false,
          placeholder: "Enter warehouse zone",
        },
        {
          id: "storageBin",
          label: "Storage Bin",
          type: "text",
          required: false,
          placeholder: "Enter storage bin",
        },
      ],
    },
    {
      id: "wr-goods",
      title: "Goods Description",
      description: "Details of stored goods",
      fields: [
        {
          id: "goodsDescription",
          label: "Goods Description",
          type: "textarea",
          required: true,
          placeholder: "Describe the goods",
          rows: 3,
        },
        {
          id: "commodityCode",
          label: "Commodity Code",
          type: "text",
          required: false,
          placeholder: "Enter commodity code",
        },
        {
          id: "hsCode",
          label: "HS Code",
          type: "text",
          required: false,
          placeholder: "Enter HS code",
        },
        {
          id: "productIdentifier",
          label: "Product Identifier",
          type: "text",
          required: false,
          placeholder: "Enter product identifier",
        },
        {
          id: "batchNumber",
          label: "Batch Number",
          type: "text",
          required: false,
          placeholder: "Enter batch number",
        },
        {
          id: "quantity",
          label: "Quantity",
          type: "number",
          required: true,
          placeholder: "0",
        },
        {
          id: "quantityUnit",
          label: "Quantity Unit",
          type: "text",
          required: true,
          placeholder: "e.g., pieces, kg, tons",
        },
        {
          id: "numberOfPackages",
          label: "Number of Packages",
          type: "number",
          required: false,
          placeholder: "0",
        },
        {
          id: "packagingType",
          label: "Packaging Type",
          type: "text",
          required: false,
          placeholder: "Enter packaging type",
        },
        {
          id: "packagingMarks",
          label: "Packaging Marks",
          type: "text",
          required: false,
          placeholder: "Enter packaging marks",
        },
      ],
    },
    {
      id: "wr-measurements",
      title: "Weight & Dimensions",
      description: "Physical measurements of goods",
      fields: [
        {
          id: "grossWeight",
          label: "Gross Weight",
          type: "number",
          required: false,
          placeholder: "0.00",
        },
        {
          id: "netWeight",
          label: "Net Weight",
          type: "number",
          required: false,
          placeholder: "0.00",
        },
        {
          id: "weightUnit",
          label: "Weight Unit",
          type: "select",
          required: false,
          options: [
            { value: "kg", label: "Kilograms (kg)" },
            { value: "lbs", label: "Pounds (lbs)" },
            { value: "tons", label: "Tons" },
          ],
        },
        {
          id: "volume",
          label: "Volume",
          type: "number",
          required: false,
          placeholder: "0.00",
        },
        {
          id: "volumeUnit",
          label: "Volume Unit",
          type: "select",
          required: false,
          options: [
            { value: "m3", label: "Cubic Meters (m³)" },
            { value: "ft3", label: "Cubic Feet (ft³)" },
          ],
        },
        {
          id: "dimensions",
          label: "Dimensions (L×W×H)",
          type: "text",
          required: false,
          placeholder: "e.g., 100×50×30 cm",
        },
      ],
    },
    {
      id: "wr-storage-charges",
      title: "Storage & Charges",
      description: "Storage conditions and charges",
      fields: [
        {
          id: "temperatureRange",
          label: "Temperature Range",
          type: "text",
          required: false,
          placeholder: "e.g., 2-8°C",
        },
        {
          id: "humidityRange",
          label: "Humidity Range",
          type: "text",
          required: false,
          placeholder: "e.g., 40-60%",
        },
        {
          id: "specialHandlingInstructions",
          label: "Special Handling Instructions",
          type: "textarea",
          required: false,
          placeholder: "Enter special handling instructions",
          rows: 3,
        },
        {
          id: "hazardClass",
          label: "Hazard Class",
          type: "text",
          required: false,
          placeholder: "Enter hazard class if applicable",
        },
        {
          id: "storageCharges",
          label: "Storage Charges",
          type: "number",
          required: false,
          placeholder: "0.00",
        },
        {
          id: "handlingCharges",
          label: "Handling Charges",
          type: "number",
          required: false,
          placeholder: "0.00",
        },
        {
          id: "otherCharges",
          label: "Other Charges",
          type: "number",
          required: false,
          placeholder: "0.00",
        },
        {
          id: "totalCharges",
          label: "Total Charges",
          type: "number",
          required: false,
          placeholder: "Auto-calculated (Storage + Handling + Other)",
          readonly: true,
          computed: true,
        },
        {
          id: "paymentTerms",
          label: "Payment Terms",
          type: "text",
          required: false,
          placeholder: "Enter payment terms",
        },
        {
          id: "paymentStatus",
          label: "Payment Status",
          type: "select",
          required: false,
          options: [
            { value: "paid", label: "Paid" },
            { value: "pending", label: "Pending" },
            { value: "overdue", label: "Overdue" },
          ],
        },
      ],
    },
  ],
}

// Bill of Lading Form Config
export const billOfLadingConfig = {
  steps: [
    blockchainFieldsStep,
    {
      id: "bol-basic-details",
      title: "Bill of Lading Details",
      description: "Basic shipping document information",
      fields: [
        {
          id: "bolId",
          label: "BOL ID",
          type: "text",
          required: true,
          placeholder: "Auto-generated",
          readonly: true,
        },
        {
          id: "documentIdentifier",
          label: "Document Identifier",
          type: "text",
          required: false,
          placeholder: "Enter document identifier",
        },
        {
          id: "bookingReference",
          label: "Booking Reference",
          type: "text",
          required: false,
          placeholder: "Enter booking reference",
        },
        {
          id: "houseWaybillId",
          label: "House Waybill ID",
          type: "text",
          required: false,
          placeholder: "Enter house waybill ID",
        },
        {
          id: "transportContractNumber",
          label: "Transport Contract Number",
          type: "text",
          required: false,
          placeholder: "Enter transport contract number",
        },
        {
          id: "contractNumber",
          label: "Contract Number",
          type: "text",
          required: false,
          placeholder: "Enter contract number",
        },
        {
          id: "freightForwarderReference",
          label: "Freight Forwarder Reference",
          type: "text",
          required: false,
          placeholder: "Enter freight forwarder reference",
        },
      ],
    },
    {
      id: "bol-dates",
      title: "Dates & Timeline",
      description: "Shipping dates and schedule",
      fields: [
        {
          id: "issueDate",
          label: "Issue Date",
          type: "date",
          required: true,
        },
        {
          id: "loadingDate",
          label: "Loading Date",
          type: "date",
          required: false,
        },
        {
          id: "estimatedDeparture",
          label: "Estimated Departure",
          type: "date",
          required: false,
        },
        {
          id: "actualDepartureDate",
          label: "Actual Departure Date",
          type: "date",
          required: false,
        },
        {
          id: "estimatedArrival",
          label: "Estimated Arrival",
          type: "date",
          required: false,
        },
        {
          id: "actualArrivalDate",
          label: "Actual Arrival Date",
          type: "date",
          required: false,
        },
      ],
    },
    {
      id: "bol-parties",
      title: "Parties Information",
      description: "All parties involved in shipment",
      fields: [
        {
          id: "buyerName",
          label: "Buyer Name",
          type: "text",
          required: false,
          placeholder: "Enter buyer name",
        },
        {
          id: "buyerAddress",
          label: "Buyer Address",
          type: "textarea",
          required: false,
          placeholder: "Enter buyer address",
          rows: 2,
        },
        {
          id: "consignorName",
          label: "Consignor Name",
          type: "text",
          required: true,
          placeholder: "Enter consignor name",
        },
        {
          id: "consignorAddress",
          label: "Consignor Address",
          type: "textarea",
          required: true,
          placeholder: "Enter consignor address",
          rows: 2,
        },
        {
          id: "consigneeName",
          label: "Consignee Name",
          type: "text",
          required: true,
          placeholder: "Enter consignee name",
        },
        {
          id: "consigneeAddress",
          label: "Consignee Address",
          type: "textarea",
          required: true,
          placeholder: "Enter consignee address",
          rows: 2,
        },
        {
          id: "carrierName",
          label: "Carrier Name",
          type: "text",
          required: true,
          placeholder: "Enter carrier name",
        },
        {
          id: "carrierLicenseNumber",
          label: "Carrier License Number",
          type: "text",
          required: false,
          placeholder: "Enter carrier license",
        },
        {
          id: "notifyPartyName",
          label: "Notify Party Name",
          type: "text",
          required: false,
          placeholder: "Enter notify party name",
        },
        {
          id: "notifyPartyContact",
          label: "Notify Party Contact",
          type: "text",
          required: false,
          placeholder: "Enter notify party contact",
        },
      ],
    },
    {
      id: "bol-locations",
      title: "Locations",
      description: "Loading, unloading, and delivery locations",
      fields: [
        {
          id: "despatchAddress",
          label: "Despatch Address",
          type: "textarea",
          required: false,
          placeholder: "Enter despatch address",
          rows: 2,
        },
        {
          id: "despatchCountryCode",
          label: "Despatch Country Code",
          type: "text",
          required: false,
          placeholder: "e.g., US, CN, SG",
        },
        {
          id: "deliveryAddress",
          label: "Delivery Address",
          type: "textarea",
          required: false,
          placeholder: "Enter delivery address",
          rows: 2,
        },
        {
          id: "deliveryCountryCode",
          label: "Delivery Country Code",
          type: "text",
          required: false,
          placeholder: "e.g., US, CN, SG",
        },
        {
          id: "unloadingPortCode",
          label: "Unloading Port Code",
          type: "text",
          required: false,
          placeholder: "Enter port code",
        },
        {
          id: "unloadingCountry",
          label: "Unloading Country",
          type: "text",
          required: false,
          placeholder: "Enter unloading country",
        },
        {
          id: "exportationCountry",
          label: "Exportation Country",
          type: "text",
          required: false,
          placeholder: "Enter exportation country",
        },
        {
          id: "originCountry",
          label: "Origin Country",
          type: "text",
          required: false,
          placeholder: "Enter origin country",
        },
      ],
    },
    {
      id: "bol-cargo",
      title: "Cargo Details",
      description: "Information about shipped cargo",
      fields: [
        {
          id: "goodsDescription",
          label: "Goods Description",
          type: "textarea",
          required: true,
          placeholder: "Describe the cargo",
          rows: 3,
        },
        {
          id: "numberOfPackages",
          label: "Number of Packages",
          type: "number",
          required: false,
          placeholder: "0",
        },
        {
          id: "packagingType",
          label: "Packaging Type",
          type: "text",
          required: false,
          placeholder: "Enter packaging type",
        },
        {
          id: "shippingMarks",
          label: "Shipping Marks",
          type: "text",
          required: false,
          placeholder: "Enter shipping marks",
        },
        {
          id: "grossWeight",
          label: "Gross Weight (kg)",
          type: "number",
          required: false,
          placeholder: "0.00",
        },
        {
          id: "netWeight",
          label: "Net Weight (kg)",
          type: "number",
          required: false,
          placeholder: "0.00",
        },
        {
          id: "volume",
          label: "Volume (m³)",
          type: "number",
          required: false,
          placeholder: "0.00",
        },
      ],
    },
    {
      id: "bol-transport",
      title: "Transport Details",
      description: "Vehicle and container information",
      fields: [
        {
          id: "journeyIdentifier",
          label: "Journey Identifier",
          type: "text",
          required: false,
          placeholder: "Enter journey identifier",
        },
        {
          id: "transportMeansId",
          label: "Transport Means ID",
          type: "text",
          required: false,
          placeholder: "Enter transport means ID",
        },
        {
          id: "vehicleRegistration",
          label: "Vehicle Registration",
          type: "text",
          required: false,
          placeholder: "Enter vehicle registration",
        },
        {
          id: "containerSizeType",
          label: "Container Size/Type",
          type: "text",
          required: false,
          placeholder: "e.g., 20ft, 40ft",
        },
        {
          id: "containerStatus",
          label: "Container Status",
          type: "text",
          required: false,
          placeholder: "Enter container status",
        },
        {
          id: "equipmentIdentifier",
          label: "Equipment Identifier",
          type: "text",
          required: false,
          placeholder: "Enter equipment identifier",
        },
        {
          id: "sealIdentifier",
          label: "Seal Identifier",
          type: "text",
          required: false,
          placeholder: "Enter seal identifier",
        },
      ],
    },
    {
      id: "bol-charges",
      title: "Freight Charges",
      description: "Shipping costs and payment",
      fields: [
        {
          id: "freightCharges",
          label: "Freight Charges",
          type: "number",
          required: false,
          placeholder: "0.00",
        },
        {
          id: "prepaidAmount",
          label: "Prepaid Amount",
          type: "number",
          required: false,
          placeholder: "0.00",
        },
        {
          id: "collectCharges",
          label: "Collect Charges",
          type: "number",
          required: false,
          placeholder: "Auto-calculated (Freight - Prepaid)",
          readonly: true,
          computed: true,
        },
        {
          id: "tradeTermsCode",
          label: "Trade Terms Code",
          type: "select",
          required: false,
          options: [
            { value: "FOB", label: "FOB - Free on Board" },
            { value: "CIF", label: "CIF - Cost, Insurance & Freight" },
            { value: "EXW", label: "EXW - Ex Works" },
            { value: "DDP", label: "DDP - Delivered Duty Paid" },
          ],
        },
        {
          id: "tradeTermsDescription",
          label: "Trade Terms Description",
          type: "textarea",
          required: false,
          placeholder: "Enter trade terms description",
          rows: 2,
        },
      ],
    },
  ],
}

// Invoice Form Config
export const invoiceConfig = {
  steps: [
    blockchainFieldsStep,
    {
      id: "invoice-basic-details",
      title: "Invoice Information",
      description: "Basic invoice details",
      fields: [
        {
          id: "invoiceId",
          label: "Invoice ID",
          type: "text",
          required: true,
          placeholder: "Auto-generated",
          readonly: true,
        },
        {
          id: "invoiceName",
          label: "Invoice Name",
          type: "text",
          required: false,
          placeholder: "Enter invoice name",
        },
        {
          id: "date",
          label: "Invoice Date",
          type: "date",
          required: true,
        },
        {
          id: "customerId",
          label: "Customer ID",
          type: "text",
          required: false,
          placeholder: "Enter customer ID",
        },
        {
          id: "terms",
          label: "Payment Terms",
          type: "text",
          required: false,
          placeholder: "Enter payment terms",
        },
      ],
    },
    {
      id: "invoice-bill-from",
      title: "Bill From Information",
      description: "Seller/issuer details",
      fields: [
        {
          id: "billFromName",
          label: "Bill From Name",
          type: "text",
          required: true,
          placeholder: "Enter your company name",
        },
        {
          id: "billFromStreetAddress",
          label: "Street Address",
          type: "text",
          required: false,
          placeholder: "Enter street address",
        },
        {
          id: "billFromCity",
          label: "City",
          type: "text",
          required: false,
          placeholder: "Enter city",
        },
        {
          id: "billFromPostalCode",
          label: "Postal Code",
          type: "text",
          required: false,
          placeholder: "Enter postal code",
        },
        {
          id: "billFromPhoneNumber",
          label: "Phone Number",
          type: "text",
          required: false,
          placeholder: "Enter phone number",
        },
      ],
    },
    {
      id: "invoice-bill-to",
      title: "Bill To Information",
      description: "Customer details",
      fields: [
        {
          id: "billToName",
          label: "Bill To Name",
          type: "text",
          required: false,
          placeholder: "Enter customer name",
        },
        {
          id: "billToEmail",
          label: "Email",
          type: "email",
          required: false,
          placeholder: "Enter customer email",
        },
        {
          id: "billToCompanyName",
          label: "Company Name",
          type: "text",
          required: false,
          placeholder: "Enter company name",
        },
        {
          id: "billToCompanyStreetAddress",
          label: "Company Street Address",
          type: "text",
          required: false,
          placeholder: "Enter street address",
        },
        {
          id: "billToCompanyCity",
          label: "Company City",
          type: "text",
          required: false,
          placeholder: "Enter city",
        },
        {
          id: "billToCompanyPostalCode",
          label: "Company Postal Code",
          type: "text",
          required: false,
          placeholder: "Enter postal code",
        },
        {
          id: "billToCompanyPhoneNumber",
          label: "Company Phone Number",
          type: "text",
          required: false,
          placeholder: "Enter phone number",
        },
      ],
    },
    {
      id: "invoice-items",
      title: "Billable Items",
      description: "Items and charges",
      fields: [
        {
          id: "billableItemsDescription",
          label: "Item Description",
          type: "textarea",
          required: false,
          placeholder: "Describe items or services",
          rows: 3,
        },
        {
          id: "billableItemsQuantity",
          label: "Quantity",
          type: "number",
          required: false,
          placeholder: "0",
        },
        {
          id: "billableItemsRate",
          label: "Rate",
          type: "number",
          required: false,
          placeholder: "0.00",
        },
        {
          id: "billableItemsAmount",
          label: "Amount",
          type: "number",
          required: false,
          placeholder: "Auto-calculated (Quantity × Rate)",
          readonly: true,
          computed: true,
        },
      ],
    },
    {
      id: "invoice-totals",
      title: "Totals & Tax",
      description: "Calculate invoice totals",
      fields: [
        {
          id: "subtotal",
          label: "Subtotal",
          type: "number",
          required: false,
          placeholder: "Auto-calculated from billable items",
          readonly: true,
          computed: true,
        },
        {
          id: "tax",
          label: "Tax Rate (%)",
          type: "number",
          required: false,
          placeholder: "Enter tax rate (e.g., 10 for 10%)",
        },
        {
          id: "taxTotal",
          label: "Tax Total",
          type: "number",
          required: false,
          placeholder: "Auto-calculated from subtotal and tax rate",
          readonly: true,
          computed: true,
        },
        {
          id: "total",
          label: "Total Amount",
          type: "number",
          required: false,
          placeholder: "Auto-calculated (Subtotal + Tax Total)",
          readonly: true,
          computed: true,
        },
      ],
    },
  ],
}

// Certificate of Origin Form Config
export const certificateOfOriginConfig = {
  steps: [
    blockchainFieldsStep,
    {
      id: "coo-basic-details",
      title: "Certificate Details",
      description: "Basic certificate information",
      fields: [
        {
          id: "cooId",
          label: "Certificate ID",
          type: "text",
          required: true,
          placeholder: "Auto-generated",
          readonly: true,
        },
        {
          id: "issueDateTime",
          label: "Issue Date & Time",
          type: "datetime-local",
          required: true,
        },
        {
          id: "firstSignatoryAuthentication",
          label: "First Signatory Authentication",
          type: "text",
          required: false,
          placeholder: "Enter authentication details",
        },
        {
          id: "signature",
          label: "Signature",
          type: "text",
          required: false,
          placeholder: "Digital signature",
        },
      ],
    },
    {
      id: "coo-consignment",
      title: "Supply Chain Consignment",
      description: "Consignment information",
      fields: [
        {
          id: "supplyChainConsignment",
          label: "Supply Chain Consignment",
          type: "text",
          required: false,
          placeholder: "Enter consignment details",
        },
        {
          id: "supplyChainConsignmentId",
          label: "Consignment ID",
          type: "text",
          required: false,
          placeholder: "Enter consignment ID",
        },
        {
          id: "supplyChainConsignmentInformation",
          label: "Consignment Information",
          type: "textarea",
          required: false,
          placeholder: "Enter consignment information",
          rows: 3,
        },
        {
          id: "includedConsignmentItems",
          label: "Included Consignment Items",
          type: "textarea",
          required: false,
          placeholder: "List consignment items",
          rows: 3,
        },
      ],
    },
    {
      id: "coo-export",
      title: "Export Information",
      description: "Exporter and export country details",
      fields: [
        {
          id: "exportCountry",
          label: "Export Country",
          type: "text",
          required: true,
          placeholder: "Enter export country",
        },
        {
          id: "exportCountryCode",
          label: "Export Country Code",
          type: "text",
          required: true,
          placeholder: "e.g., US, CN, SG",
        },
        {
          id: "exporter",
          label: "Exporter",
          type: "text",
          required: false,
          placeholder: "Enter exporter",
        },
        {
          id: "exporterId",
          label: "Exporter ID",
          type: "text",
          required: false,
          placeholder: "Enter exporter ID",
        },
        {
          id: "exporterName",
          label: "Exporter Name",
          type: "text",
          required: true,
          placeholder: "Enter exporter company name",
        },
        {
          id: "exporterLine1",
          label: "Exporter Address Line 1",
          type: "text",
          required: false,
          placeholder: "Enter address line 1",
        },
        {
          id: "exporterLine2",
          label: "Exporter Address Line 2",
          type: "text",
          required: false,
          placeholder: "Enter address line 2",
        },
        {
          id: "exporterCityName",
          label: "Exporter City",
          type: "text",
          required: false,
          placeholder: "Enter city",
        },
        {
          id: "exporterPostcode",
          label: "Exporter Postcode",
          type: "text",
          required: false,
          placeholder: "Enter postcode",
        },
        {
          id: "exporterCountrySubDivisionName",
          label: "Exporter State/Province",
          type: "text",
          required: false,
          placeholder: "Enter state or province",
        },
        {
          id: "exporterCountryCode",
          label: "Exporter Country Code",
          type: "text",
          required: false,
          placeholder: "Enter country code",
        },
      ],
    },
    {
      id: "coo-import",
      title: "Import Information",
      description: "Importer and import country details",
      fields: [
        {
          id: "importCountry",
          label: "Import Country",
          type: "text",
          required: true,
          placeholder: "Enter import country",
        },
        {
          id: "importCountryCode",
          label: "Import Country Code",
          type: "text",
          required: true,
          placeholder: "e.g., US, CN, SG",
        },
        {
          id: "importer",
          label: "Importer",
          type: "text",
          required: false,
          placeholder: "Enter importer",
        },
        {
          id: "importerId",
          label: "Importer ID",
          type: "text",
          required: false,
          placeholder: "Enter importer ID",
        },
        {
          id: "importerName",
          label: "Importer Name",
          type: "text",
          required: true,
          placeholder: "Enter importer company name",
        },
        {
          id: "importerLine1",
          label: "Importer Address Line 1",
          type: "text",
          required: false,
          placeholder: "Enter address line 1",
        },
        {
          id: "importerLine2",
          label: "Importer Address Line 2",
          type: "text",
          required: false,
          placeholder: "Enter address line 2",
        },
        {
          id: "importerCityName",
          label: "Importer City",
          type: "text",
          required: false,
          placeholder: "Enter city",
        },
        {
          id: "importerPostcode",
          label: "Importer Postcode",
          type: "text",
          required: false,
          placeholder: "Enter postcode",
        },
        {
          id: "importerCountrySubDivisionName",
          label: "Importer State/Province",
          type: "text",
          required: false,
          placeholder: "Enter state or province",
        },
        {
          id: "importerCountryCode",
          label: "Importer Country Code",
          type: "text",
          required: false,
          placeholder: "Enter country code",
        },
      ],
    },
    {
      id: "coo-loading",
      title: "Loading Location",
      description: "Loading baseport information",
      fields: [
        {
          id: "loadingBaseportLocation",
          label: "Loading Baseport Location",
          type: "text",
          required: false,
          placeholder: "Enter loading location",
        },
        {
          id: "loadingBaseportLocationId",
          label: "Loading Baseport ID",
          type: "text",
          required: false,
          placeholder: "Enter location ID",
        },
        {
          id: "loadingBaseportLocationName",
          label: "Loading Baseport Name",
          type: "text",
          required: false,
          placeholder: "Enter location name",
        },
      ],
    },
    {
      id: "coo-transport",
      title: "Transport Movement",
      description: "Main carriage transport details",
      fields: [
        {
          id: "mainCarriageTransportMovement",
          label: "Main Carriage Transport Movement",
          type: "text",
          required: false,
          placeholder: "Enter transport movement",
        },
        {
          id: "mainCarriageTransportMovementId",
          label: "Transport Movement ID",
          type: "text",
          required: false,
          placeholder: "Enter movement ID",
        },
        {
          id: "mainCarriageTransportMovementInformation",
          label: "Transport Movement Information",
          type: "textarea",
          required: false,
          placeholder: "Enter movement information",
          rows: 3,
        },
        {
          id: "usedTransportMeansName",
          label: "Transport Means Name",
          type: "text",
          required: false,
          placeholder: "e.g., vessel name",
        },
        {
          id: "usedTransportMeansId",
          label: "Transport Means ID",
          type: "text",
          required: false,
          placeholder: "Enter transport means ID",
        },
        {
          id: "departureDateTime",
          label: "Departure Date & Time",
          type: "datetime-local",
          required: false,
        },
      ],
    },
    {
      id: "coo-unloading",
      title: "Unloading Location",
      description: "Unloading baseport information",
      fields: [
        {
          id: "unloadingBaseportLocation",
          label: "Unloading Baseport Location",
          type: "text",
          required: false,
          placeholder: "Enter unloading location",
        },
        {
          id: "unloadingBaseportLocationId",
          label: "Unloading Baseport ID",
          type: "text",
          required: false,
          placeholder: "Enter location ID",
        },
        {
          id: "unloadingBaseportLocationName",
          label: "Unloading Baseport Name",
          type: "text",
          required: false,
          placeholder: "Enter location name",
        },
      ],
    },
  ],
}

export const formConfigs = {
  "electronic-promissory-note": electronicPromissoryNoteConfig,
  "warehouse-receipt": warehouseReceiptConfig,
  "bill-of-lading": billOfLadingConfig,
  invoice: invoiceConfig,
  "certificate-of-origin": certificateOfOriginConfig,
}
